version: '3'
services:
  rbbdockerregnginx:
    image: registry_rbbdockerregnginx:1.15.2
    container_name: rbbdockerregnginx
    labels:
      com.rbbdockerreg.description: "RBB Private Registry"
      com.rbbdockerreg.department: "TPS-O"
    build:
      context: ./registry_dockerfile_nginx
      dockerfile: Dockerfile
    ports:
      - 5043:443
    links:
      - rbbdockerreg:registry
    volumes:
      - ./registry_data_nginx/:/etc/nginx/conf.d

  rbbdockerreg:
    image: registry_rbbdockerreg:2.6.2
    container_name: rbbdockerreg
    labels:
      com.rbbdockerreg.description: "RBB Private Registry"
      com.rbbdockerreg.department: "TPS-O"
    build:
      context: ./registry_dockerfile
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry_data:/data

##########################################################
# Test if it is working: curl http://localhost:5000/v2/
# OUTPUT: {}
# DockerOUTPUT:
# rbbdockerreg         | time="2018-08-08T13:31:16Z" level=info msg="response completed" go.version=go1.7.6 http.request.host="127.0.0.1:5000" http.request.id=02ceb67f-f404-4277-a84c-39feee0216d9 http.request.method=GET http.request.remoteaddr="192.168.48.1:38350" http.request.uri="/v2/" http.request.useragent="curl/7.54.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.01551ms http.response.status=200 http.response.written=2 instance.id=2422cb38-9024-491f-981e-90cb4c3948b4 version=v2.6.2 
# rbbdockerreg         | 192.168.48.1 - - [08/Aug/2018:13:31:16 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.54.0"
##########################################################
