FROM opensuse/portus:2.3
# http://port.us.org/docs/deploy.html
# Main Repo: https://github.com/SUSE/Portus/tree/master/docker

MAINTAINER Manuel Geyer <manuel.geyer@rbb-online.de>
USER root
RUN mkdir -p /usr/local/share/ca-certificates/docker-dev-cert 
            #/usr/local/share/ca-certificates/docker-dev-cert/devdockerCA.crt
